# Run using docker compose --env-file ./docker/env_files/nfc-dev-server.env -f docker-compose-dev-server.yml up
services:
  mongo:
    container_name: mongodb_nst
    image: mongo:7.0
    restart: always
    env_file:
      - path: ./docker/env_files/nfc-dev-server.env
        required: true
    volumes:
      - mongodbdata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://localhost:27017" --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mongo-express:
    container_name: mongo-express_nst
    image: mongo-express:1
    restart: always
    env_file:
      - path: ./docker/env_files/nfc-dev-server.env
        required: true
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy

  nfc:
    container_name: nfc-sample-tracker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - path: ./docker/env_files/nfc-dev-server.env
        required: true
    ports:
      - 8083:8083
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - nstdata:/nstdata
      - .:/nfc-sample-tracker:ro

volumes:
  mongodbdata:
  nstdata:
